/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OpenAcl_CONSTANTS_H
#define OpenAcl_CONSTANTS_H

#include "OpenAcl_types.h"



class OpenAclConstants {
 public:
  OpenAclConstants();

};

extern const OpenAclConstants g_OpenAcl_constants;



#endif
