/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OpenAcl_constants.h"



const OpenAclConstants g_OpenAcl_constants;

OpenAclConstants::OpenAclConstants() {
}



